Make python spout manager tolerant of exceptions
pachyderm/python-pachyderm pull request #225
Opened 2020-09-14 16:35 UTC by msteffen

Just creating this PR in preparation for the oncall handoff. We probably need a test for this as well, plus a new release

2020-09-14 16:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pachyderm/python-pachyderm?pullRequest=225) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pachyderm/python-pachyderm?pullRequest=225) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pachyderm/python-pachyderm?pullRequest=225) it.</sub>

2020-09-14 16:40 UTC, lukemarsden requested changes
Thank you for working on this! It should be easy to add a test for this, just copy the whole test around https://github.com/pachyderm/python-pachyderm/blob/master/tests/test_spout.py#L16 and make that line `raise Exception("boom!")` (with approprate `try: except` in the test to avoid failing the test) and then assert that it's able to further call `with manager.commit()` without error.

Feel free to raise a followup issue for adding the test coverage, but -- it might be easier to write the test than to test it manually.

2020-09-14 16:40 UTC, lukemarsden commented on src/python_pachyderm/spout.py
>          self._has_open_commit = False
Need to set `_has_open_commit = False` in this case too. (i.e. indent this line)

2020-09-14 16:44 UTC, lukemarsden commented
Also, I'm curious why there's an existing test which asserts the opposite of the behavior in this PR:

https://github.com/pachyderm/python-pachyderm/blob/master/tests/test_spout.py#L34-L42

2020-09-14 16:50 UTC, msteffen commented
> Also, I'm curious why there's an existing test which asserts the opposite of the behavior in this PR:
> 
> https://github.com/pachyderm/python-pachyderm/blob/master/tests/test_spout.py#L34-L42
> 
> I wonder if (as the existing test suggests) we want the commit to stay open in the case where we error out? If so, how's the user meant to close it?

That is a great question. I made the python fix you suggested, and I'll note in the question about the test in the handoff document.

I can try to get in touch with @ysimonson, but if we can't figure it out, then I think it might make sense to just reverse the test? Under the rationale that if we're wrong, at least this way we'll find out why :shrug:

2020-09-14 16:54 UTC, lukemarsden approved these changes

2020-09-14 16:58 UTC, lukemarsden commented
I'm fine with the change as-is on the basis of the rationale that once the `with` scope has exited, it ought to have released the resource it represented. Hopefully you'll also need to reverse the test to make the suite pass (`assert not manager._has_open_commit` on https://github.com/pachyderm/python-pachyderm/blob/master/tests/test_spout.py#L42), which would be a minimal change to get this merged. A test which also re-uses the manager to check that it works after an error would be great too.

2020-09-14 19:13 UTC, ysimonson commented
I can't recall, but my guess is that it felt "wrong" to close the spout commit on exception. It seems that this change would be more in keeping with context managers though:

```
>>> with open("foo.txt", "w") as f:
...     f.write("hi")
...     raise Exception()
...
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
Exception
>>> f.closed
True
```

2020-09-17 09:11 UTC, msteffen commented
This repo seems to be in somewhat unfortunate shape at the moment. I don't think it has any kind of CI set up, and when I ran the full test suite locally to make sure everything passed before I merged, the tests I added pass, but `test_pps` seems to permanently break the Pachyderm 1.11 cluster I'm testing this against for some reason that I don't understand:
```
$ kc logs po/pipeline-test-create-pipeline-from-request-vaj7i6-v1-97vbg --previous user
2020-09-17T09:07:00Z ERROR could not read existing PipelineInfo from PFS: commit a8f11115570549c9bdcff0ae2589ae0d not found in repo __spec__
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x209271f]

goroutine 1 [running]:
github.com/pachyderm/pachyderm/src/server/worker/driver.NewDriver(0xc0000da8c0, 0xc0000b6240, 0xc000352f00, 0xc000054040, 0x1d, 0xc00005601a, 0x5, 0x28563f6, 0x1, 0xc00005200f, ...)
	/app/src/server/worker/driver/driver.go:248 +0x93f
github.com/pachyderm/pachyderm/src/server/worker.NewWorker(0xc0000b6240, 0xc000352f00, 0xc000054040, 0x1d, 0xc0000da8c0, 0xc0000500ad, 0x3a, 0xc00005200f, 0x7, 0xc00005601a, ...)
	/app/src/server/worker/worker.go:65 +0xf1
main.do(0x2331a00, 0xc00040f5f0, 0x0, 0x0)
	/app/src/server/cmd/worker/main.go:86 +0x1b9
github.com/pachyderm/pachyderm/src/server/pkg/cmdutil.Main(0x294c960, 0x2331a00, 0xc00040f5f0, 0x0, 0x0, 0x0)
	/app/src/server/pkg/cmdutil/env.go:33 +0x83
main.main()
	/app/src/server/cmd/worker/main.go:42 +0x12e

$ pc list pipeline
commit a8f11115570549c9bdcff0ae2589ae0d not found in repo __spec__
```

I don't think it's safe to merge this PR until we understand the error, unfortunately (I think it's a bug in core Pachyderm, but I don't want to distribute a python-pachyderm package that triggers an open bug), so I think this PR will probably languish until we figure out that issue.

2020-09-17 15:04 UTC, ysimonson commented
CI is activated on the repo, it's not showing up in the PR checks due to some issue either with the config or with TravisCI itself: https://travis-ci.org/github/pachyderm/python-pachyderm

2020-09-17 15:05 UTC, ysimonson commented
If you run tests locally, make sure to go through the local testing instructions: https://github.com/pachyderm/python-pachyderm/blob/master/contributing.md#testing

2020-09-17 17:38 UTC, msteffen commented
> CI is activated on the repo, it's not showing up in the PR checks due to some issue either with the config or with TravisCI itself: https://travis-ci.org/github/pachyderm/python-pachyderm

This is all really helpful! Thanks!

I'll figure out why this PR isn't working in CI before I merge anything then. As far as the PPS issue, I think that's actually a pachyderm bug, and I think fixing that will be separate :shrug:

2021-03-25 12:54 UTC, merged